front_office:
    resource: "@FrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /

back_office:
    resource: "@BackOfficeBundle/Resources/config/routing.yml"
    prefix:   /adminbo

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
