front_office_homepage:
    path:     /
    defaults: { _controller: FrontOfficeBundle:Default:index }

home:
    path:     /home
    defaults: { _controller: FrontOfficeBundle:Default:index }

readTrajet:
    path:     /readTrajet
    defaults: { _controller: FrontOfficeBundle:Trajet:read }

showTrajet:
    path: /showTrajet/{id}
    defaults: { _controller: FrontOfficeBundle:Trajet:show }

addTrajet:
    path:     /addTrajet
    defaults: { _controller: FrontOfficeBundle:Trajet:add }

editTrajet:
    path: /editTrajet/{id}
    defaults: { _controller: FrontOfficeBundle:Trajet:edit }

deleteTrajet:
    path: /deleteTrajet/{id}
    defaults: { _controller: FrontOfficeBundle:Trajet:delete }

getDistance:
    path: /getDistance/{id}
    defaults: { _controller: FrontOfficeBundle:Trajet:getDistance}
