front_office_homepage:
    path:     /
    defaults: { _controller: FrontOfficeBundle:Default:index }

home:
    path:     /home
    defaults: { _controller: FrontOfficeBundle:Default:index }

trajet:
    path:     /trajet
    defaults: { _controller: FrontOfficeBundle:Trajet:read }

showTrajet:
    path: /showTrajet/{id}
    defaults: { _controller: FrontOfficeBundle:Trajet:show }
