index:
    path: /
    defaults: { _controller: BackOfficeBundle:Default:index }

backHome:
    path: /home
    defaults: { _controller: BackOfficeBundle:Default:index }

readVoiture:
    path: /readVoiture
    defaults: { _controller: BackOfficeBundle:Voiture:read }

addVoiture:
    path: /addVoiture
    defaults: { _controller: BackOfficeBundle:Voiture:add }

editVoiture:
    path: /editVoiture/{id}
    defaults: { _controller: BackOfficeBundle:Voiture:edit }

deleteVoiture:
    path: /deleteVoiture/{id}
    defaults: { _controller: BackOfficeBundle:Voiture:delete }

addMarque:
    path: /addMarque
    defaults: { _controller: BackOfficeBundle:Voiture:addMarque }

readStatistiques:
    path: /readStatistiques
    defaults: { _controller: BackOfficeBundle:Statistiques:read }

readVille:
    path: /readVille
    defaults: { _controller: BackOfficeBundle:Ville:read }

addVille:
    path: /addVille
    defaults: { _controller: BackOfficeBundle:Ville:add }

editVille:
    path: /editVille/{id}
    defaults: { _controller: BackOfficeBundle:Ville:edit }

deleteVillz:
    path: /deleteVille/{id}
    defaults: { _controller: BackOfficeBundle:Ville:delete }
