index:
    path: /
    defaults: { _controller: BackOfficeBundle:Default:index }

backHome:
    path: /home
    defaults: { _controller: BackOfficeBundle:Default:index }

readInternaute:
    path: /readInternaute
    defaults: { _controller: BackOfficeBundle:Internaute:read }

addInternaute:
    path: /addInternaute
    defaults: { _controller: BackOfficeBundle:Internaute:add }

addInternaute:
    path: /addInternaute/{marqueId}
    defaults: { _controller: BackOfficeBundle:Internaute:add }

editInternaute:
    path: /editInternaute/{id}
    defaults: { _controller: BackOfficeBundle:Internaute:edit }

deleteInternaute:
    path: /deleteInternaute/{id}
    defaults: { _controller: BackOfficeBundle:Internaute:delete }

readVoiture:
    path: /readVoiture
    defaults: { _controller: BackOfficeBundle:Voiture:read }

addVoiture:
    path: /addVoiture
    defaults: { _controller: BackOfficeBundle:Voiture:add }

editVoiture:
    path: /editVoiture/{id}
    defaults: { _controller: BackOfficeBundle:Voiture:edit }

deleteVoiture:
    path: /deleteVoiture/{id}
    defaults: { _controller: BackOfficeBundle:Voiture:delete }

addMarque:
    path: /addMarque
    defaults: { _controller: BackOfficeBundle:Voiture:addMarque }

readStatistiques:
    path: /readStatistiques
    defaults: { _controller: BackOfficeBundle:Statistiques:read }

readVille:
    path: /readVille
    defaults: { _controller: BackOfficeBundle:Ville:read }

addVille:
    path: /addVille
    defaults: { _controller: BackOfficeBundle:Ville:add }

editVille:
    path: /editVille/{id}
    defaults: { _controller: BackOfficeBundle:Ville:edit }

deleteVille:
    path: /deleteVille/{id}
    defaults: { _controller: BackOfficeBundle:Ville:delete }

readInscription:
    path: /readInscription
    defaults: { _controller: BackOfficeBundle:Inscription:read }

participant:
    path: /participant/{id}
    defaults: { _controller: BackOfficeBundle:Inscription:participant }

addPassager:
    path: /addPassager/{id}
    defaults: { _controller: BackOfficeBundle:Inscription:addPassager }

deletePassager:
    path: /deletePassager/{idTrajet}/{idPassager}
    defaults: { _controller: BackOfficeBundle:Inscription:deletePassager }
