index:
    path: /
    defaults: { _controller: BackOfficeBundle:Default:index }

home:
    path: /home
    defaults: { _controller: BackOfficeBundle:Default:index }

readVoiture:
    path: /readVoiture
    defaults: { _controller: BackOfficeBundle:Voiture:read }

addVoiture:
    path: /addVoiture
    defaults: { _controller: BackOfficeBundle:Voiture:add }

readStatistiques:
    path: /readStatistiques
    defaults: { _controller: BackOfficeBundle:Statistiques:read }

readVille:
    path: /readVille
    defaults: { _controller: BackOfficeBundle:Ville:read }

addVille:
    path: /addVille
    defaults: { _controller: BackOfficeBundle:Ville:add }
