<?php

namespace BackOfficeBundle\Repository;

/**
 * inscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class inscriptionRepository extends \Doctrine\ORM\EntityRepository
{
	public function findPassagers($id)
	{	
		return $this->getEntityManager()
			->createQuery(
		    'SELECT user.id as id, user.nom as nom, user.prenom as prenom
		    FROM BackOfficeBundle:Inscription inscription
		    JOIN BackOfficeBundle:Internaute user WITH user.id=inscription.internaute
		    WHERE inscription.trajet = :id')
			->setParameter('id', $id)
		    ->getResult();
	}

	public function findPassager($idTrajet, $idPassager)
	{
		return $this->getEntityManager()
			->createQuery(
		    'SELECT inscription
		    FROM BackOfficeBundle:Inscription inscription
		    JOIN BackOfficeBundle:Internaute user WITH user.id=inscription.internaute
		    WHERE inscription.trajet = :idTrajet and inscription.internaute = :idPassager')
			->setParameter('idTrajet', $idTrajet)
			->setParameter('idPassager', $idPassager)
		    ->getResult();
	}

	public function countPassager($id)
	{
		return $this->getEntityManager()
			->createQuery(
			'SELECT count(inscription) as nbPassager
			FROM BackOfficeBundle:Inscription inscription
			WHERE inscription.trajet= :id')
			->setParameter('id', $id)
			->getResult();
	}

}