<?php

namespace BackOfficeBundle\Repository;

/**
 * trajetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class trajetRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAll()
  {
    return $this->getEntityManager()
    ->createQuery(
    	'SELECT trajet.nbKm as nbKm, trajet.date as date, cityDep.ville as villeDep, cityArr.ville as villeArr, user.nom as nom, user.prenom as prenom
    	FROM BackOfficeBundle:Trajet trajet
      JOIN BackOfficeBundle:Ville cityDep WITH cityDep.id=trajet.villeDep
      JOIN BackOfficeBundle:Ville cityArr WITH cityArr.id=trajet.villeArr
    	JOIN BackOfficeBundle:Internaute user WITH user.id=trajet.internaute'
    )
    ->getResult();
  }
  public function findAllOrderedByName($slug)
  {
  	$search = $slug;
  	$search .= "%";
  	return $this->getEntityManager()
  		->createQuery(
  			'SELECT internaute FROM BackOfficeBundle:Internaute internaute WHERE internaute.actif=1 AND UPPER(internaute.nom) LIKE UPPER(:search) ORDER BY internaute.nom ASC'
  		)
  		->setParameter('search', $search)
  		->getResult();
  }
}
