<?php

namespace BackOfficeBundle\Repository;

/**
 * trajetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class trajetRepository extends \Doctrine\ORM\EntityRepository
{
}
