<?php

namespace BackOfficeBundle\Repository;

/**
 * trajetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class trajetRepository extends \Doctrine\ORM\EntityRepository
{
  public function list($id)
  {
    return $this->getEntityManager()->createQuery(
      'SELECT trajet
      FROM BackOfficeBundle:Trajet trajet
      WHERE trajet.internaute = :internaute_id'
    )->setParameters(array('internaute_id' => $id))->getResult();
  }
}
