<?php

namespace BackOfficeBundle\Repository;

/**
 * voitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class voitureRepository extends \Doctrine\ORM\EntityRepository
{

	public function findVoitureWithMarque()
	{	
		return $this->getEntityManager()
			->createQuery(
		    'SELECT voiture.id as id, voiture.modele as modele, marques.id as marque
		    FROM BackOfficeBundle:Voiture voiture
		    JOIN BackOfficeBundle:Marque marques WITH marques.id=voiture.marque'
		  	)->getResult();
	}

}
