<?php

namespace BackOfficeBundle\Repository;

/**
 * voitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class voitureRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAll()
  	{
	    return $this->getEntityManager()
	    ->createQuery(
	    	'SELECT voiture.id as id, marque.nom as marque, voiture.modele as modele, voiture.nbPlaces as nbPlaces
	    	FROM BackOfficeBundle:Voiture voiture
	    	JOIN BackOfficeBundle:Marque marque WITH marque.id=voiture.marque'
	    )
	    ->getResult();
	  	}
	}
